elems:

<% get_var!(:"wireless.interfaces").each do |interface| %>
  - src:  wpa_supplicant\.conf$
    dst:  /etc/wpa_supplicant/wpa_supplicant-<%= interface %>.conf
    only: f?wpa_supplicant
<% end %>
